![](https://img.freepik.com/free-vector/memory-storage-concept-illustration_114360-3446.jpg?t=st=1716383807~exp=1716387407~hmac=d78af4a79544b49d43d94d9cecbbc48f5ed3efc3ec5fa14fad24faeffb81fb75&w=826)

# Leitura de Revisão
## Python SQLite3: Aprenda a utilizar o banco de dados SQLite3 com Python

Python SQLite3: Aprenda a utilizar o módulo SQLite3 do Python para criar, conectar e gerenciar bancos de dados SQLite3. 

### O que é o Python SQLite3 e por que utilizá-lo para trabalhar com bancos de dados?

Python SQLite3 é um módulo integrado ao Python que permite a interação com o banco de dados SQLite3. O SQLite3 é um banco de dados leve, rápido e fácil de usar, que não requer instalação de um servidor separado. Ele é amplamente utilizado em aplicativos de desktop, mobile e web, devido à sua simplicidade e eficiência.

### Razões para utilizar o Python SQLite3

Python SQLite3 é um módulo integrado ao Python que permite a interação com o banco de dados SQLite3. O SQLite3 é um banco de dados leve, rápido e fácil de usar, que não requer instalação de um servidor separado. Ele é amplamente utilizado em aplicativos de desktop, mobile e web, devido à sua simplicidade e eficiência.

### Razões para utilizar o Python SQLite3

Existem várias razões pelas quais você deve considerar utilizar o Python SQLite3 para trabalhar com bancos de dados. Aqui estão algumas delas:

### Facilidade de uso

O Python SQLite3 oferece uma interface simples e intuitiva para interagir com o banco de dados SQLite3. Com apenas algumas linhas de código, você pode criar, conectar, consultar e modificar o banco de dados.

### Portabilidade

O SQLite3 é um banco de dados embutido, o que significa que o arquivo do banco de dados é armazenado localmente no sistema de arquivos. Isso o torna altamente portátil, permitindo que você mova facilmente o banco de dados entre diferentes sistemas operacionais e plataformas.

### Baixo consumo de recursos

O SQLite3 é projetado para ser leve e eficiente em termos de consumo de recursos. Ele não requer muita memória ou poder de processamento, o que o torna ideal para dispositivos com recursos limitados, como smartphones e sistemas embarcados.

### Ampla adoção

O SQLite3 é um dos bancos de dados mais populares do mundo, com uma grande comunidade de desenvolvedores e uma vasta quantidade de recursos e documentação disponíveis. Isso significa que você pode encontrar facilmente suporte e soluções para qualquer problema que possa surgir ao utilizar o Python SQLite3.

### Como instalar o módulo SQLite3 no Python e configurar o ambiente de desenvolvimento?

ara utilizar o módulo SQLite3 no Python, você precisa garantir que ele esteja instalado e configurado corretamente em seu ambiente de desenvolvimento. Aqui estão os passos necessários para fazer isso:

#### 1. Verifique a versão do Python

Antes de prosseguir, verifique se você tem o Python instalado em seu sistema. Abra o terminal ou prompt de comando e digite python --version para verificar a versão instalada. Certifique-se de ter pelo menos o Python 3.6 ou superior.

#### 2. Instale o módulo SQLite3

O módulo SQLite3 já é incluído na biblioteca padrão do Python, portanto, não é necessário instalá-lo separadamente. No entanto, você pode verificar se ele está disponível digitando import sqlite3 no interpretador Python. Se não houver erros, significa que o módulo está instalado corretamente.

#### 3. Crie um ambiente virtual (opcional)

Para manter seu ambiente de desenvolvimento limpo e isolado, é recomendável criar um ambiente virtual para o seu projeto. Use a ferramenta venv do Python para criar um novo ambiente virtual e ativá-lo usando o comando apropriado para o seu sistema operacional.

#### 4. Importe o módulo SQLite3

Em seu código Python, importe o módulo SQLite3 usando a declaração import sqlite3. Isso tornará todas as funcionalidades do SQLite3 disponíveis para uso em seu programa.

#### 5. Conecte-se ao banco de dados

Para começar a interagir com um banco de dados SQLite3, você precisa estabelecer uma conexão com o arquivo do banco de dados. Use a função connect() do módulo SQLite3, passando o caminho para o arquivo do banco de dados como argumento.

#### 6. Execute comandos SQL

Após estabelecer a conexão, você pode executar comandos SQL no banco de dados. Use o método execute() do objeto de conexão para enviar consultas e comandos SQL para o banco de dados. Você também pode usar os métodos fetchone() e fetchall() para recuperar os resultados das consultas.

#### 7. Feche a conexão

Sempre que terminar de usar o banco de dados, é importante fechar a conexão para liberar recursos. Use o método close() do objeto de conexão para fazer isso.

Com o módulo SQLite3 instalado e configurado corretamente, você está pronto para começar a utilizar o Python SQLite3 para trabalhar com bancos de dados SQLite3 em seus projetos. Aprenda a criar, conectar e gerenciar um banco de dados SQLite3 utilizando o Python e aproveite todos os benefícios que essa combinação poderosa tem a oferecer.

### Aprenda a criar, conectar e gerenciar um banco de dados SQLite3 utilizando o Python.

O Python SQLite3 oferece uma série de recursos que permitem criar, conectar e gerenciar um banco de dados SQLite3 de maneira eficiente e conveniente. Nesta seção, vamos explorar os principais passos para realizar essas tarefas.

#### 1. Criando um banco de dados

Para criar um banco de dados SQLite3, você pode utilizar o módulo SQLite3 do Python para executar comandos SQL. Por exemplo, você pode executar a seguinte instrução SQL para criar um novo banco de dados:

```python
import sqlite3

  # Conectando ao banco de dados (caso não exista, será criado)
  conn = sqlite3.connect('nome_do_banco.db')
```

#### 2. Conectando ao banco de dados

Após criar o banco de dados, é necessário estabelecer uma conexão com ele para realizar operações. Utilize a função connect() do módulo SQLite3, passando o caminho para o arquivo do banco de dados como argumento. Por exemplo:

```python
import sqlite3

  # Conectando ao banco de dados existente
  conn = sqlite3.connect('nome_do_banco.db')
```

#### 3. Executando comandos SQL

Com a conexão estabelecida, você pode executar comandos SQL para realizar operações no banco de dados. Utilize o método execute() do objeto de conexão para enviar consultas e comandos SQL. Por exemplo:

```python
import sqlite3

  # Conectando ao banco de dados existente
  conn = sqlite3.connect('nome_do_banco.db')

  # Executando um comando SQL para criar uma tabela
  conn.execute('CREATE TABLE IF NOT EXISTS usuarios (id INTEGER PRIMARY KEY, nome TEXT, idade INTEGER)')
```

#### 4. Inserindo dados

Para inserir dados em uma tabela do banco de dados, utilize o comando INSERT INTO seguido pelo nome da tabela e os valores a serem inseridos. Por exemplo:

```python
import sqlite3

  # Conectando ao banco de dados existente
  conn = sqlite3.connect('nome_do_banco.db')

  # Inserindo um novo usuário na tabela
  conn.execute("INSERT INTO usuarios (nome, idade) VALUES ('João', 25)")
```

#### 5. Atualizando dados

Para atualizar registros existentes em uma tabela, utilize o comando UPDATE seguido pelo nome da tabela, os campos a serem atualizados e as condições para a atualização. Por exmplo:

```python
import sqlite3

  # Conectando ao banco de dados existente
  conn = sqlite3.connect('nome_do_banco.db')

  # Atualizando a idade de um usuário
  conn.execute("UPDATE usuarios SET idade = 26 WHERE nome = 'João'")
```

#### 6. Excluindo dados

Para excluir registros de uma tabela, utilize o comando DELETE FROM seguido pelo nome da tabela e as condições para a exclusão. Por exemplo:

```python
import sqlite3

  # Conectando ao banco de dados existente
  conn = sqlite3.connect('nome_do_banco.db')

  # Excluindo um usuário da tabela
  conn.execute("DELETE FROM usuarios WHERE nome = 'João'")
```

### Explorando as principais funcionalidades do Python SQLite3: consultas, inserções, atualizações e exclusões de dados.

Com o Python SQLite3, você pode realizar diversas operações relacionadas a consultas, inserções, atualizações e exclusões de dados em um banco de dados SQLite3. Vamos explorar cada uma dessas funcionalidades em detalhes.

#### Consultas

Para realizar consultas em um banco de dados SQLite3, utilize o comando SELECT seguido pelos campos desejados e as condições de filtragem. Por exemplo:

```python
import sqlite3

  # Conectando ao banco de dados existente
  conn = sqlite3.connect('nome_do_banco.db')

  # Realizando uma consulta para recuperar todos os usuários com idade maior que 20
  consulta = conn.execute("SELECT * FROM usuarios WHERE idade > 20")

  # Percorrendo os resultados da consulta
  for row in consulta:
      print(row)
```

#### Inserções

Para inserir dados em uma tabela, utilize o comando INSERT INTO seguido pelo nome da tabela e os valores a serem inseridos. Por exemplo:

```python
import sqlite3

  # Conectando ao banco de dados existente
  conn = sqlite3.connect('nome_do_banco.db')

  # Inserindo um novo usuário na tabela
  conn.execute("INSERT INTO usuarios (nome, idade) VALUES ('Maria', 30)")
```

#### Atualizações

Para atualizar registros existentes em uma tabela, utilize o comando UPDATE seguido pelo nome da tabela, os campos a serem atualizados e as condições para a atualização. Por exemplo:

```python
import sqlite3

  # Conectando ao banco de dados existente
  conn = sqlite3.connect('nome_do_banco.db')

  # Atualizando a idade de um usuário
  conn.execute("UPDATE usuarios SET idade = 31 WHERE nome = 'Maria'")
```

#### Exclusões

Para excluir registros de uma tabela, utilize o comando DELETE FROM seguido pelo nome da tabela e as condições para a exclusão. Por exemplo:

```python
import sqlite3

  # Conectando ao banco de dados existente
  conn = sqlite3.connect('nome_do_banco.db')

  # Excluindo um usuário da tabela
  conn.execute("DELETE FROM usuarios WHERE nome = 'Maria'")
```

Aprenda a utilizar o banco de dados SQLite3 com Python e explore todas essas funcionalidades para criar, conectar, gerenciar, consultar, inserir, atualizar e excluir dados de forma eficiente e flexível. O Python SQLite3 é uma ferramenta poderosa que facilita o trabalho com bancos de dados, proporcionando um ambiente simples e eficaz para suas necessidades de armazenamento e recuperação de dados.

Referências: 

Awari by Fluency . <https://awari.com.br/> . Acessado em 22/05/2024.

# Banco de Dados 3

Preparação corra 🏃‍♂️‍➡️ os seguintes códigos:

```python
# Chamando bibliotecas - banco de dados
import sqlite3 
from contextlib import closing
```

```python
# Criando um banco de dados (Create)
conexão = sqlite3.connect("agenda.db")
cursor = conexão.cursor()
cursor.execute(''' create table agenda(nome text,telefone text) ''')
cursor.execute('''insert into agenda (nome, telefone) values(?,?)''', ("Nilo","7788-1432"))
conexão.commit()
cursor.close()
conexão.close
```

```python
# Inserindo registros (Create)
dados = [("João","98901-0109"),
("André","98902-8900"),
("Maria","97891-3321")]
conexão = sqlite3.connect("agenda.db")
cursor = conexão.cursor()
cursor.executemany(''' 
    insert into agenda(nome,telefone)
    values(?,?)
 ''',dados)
conexão.commit()
cursor.close()
conexão.close()
```

```python
# Pesquisando um banco de dados (Recover)
from contextlib import closing 
with sqlite3.connect('agenda.db') as conexão:
    with closing(conexão.cursor()) as cursor:
        cursor.execute("select * from agenda")
        while True:
            resultado = cursor.fetchone()
            if resultado is None:
                break
            print(f'Nome: {resultado[0]} \nTelefone: {resultado[1]}')
```

# Banco de Dados 3

## Acessando os campos como em um dicionário

Acessar os campos por posição nem sempre é tão fácil. Em python, usando SQLite, podemos acessá-los pelo nome, adicionando uma linha:

```python
conexão.row_factory = sqlite3.Row
```

Vejamos o programa completo:

```python
import sqlite3
from contextlib import closing

with sqlite3.connect("agenda.db") as conexão:
    conexão.row_factory = sqlite3.Row
    with closing(conexão.cursor()) as cursor:
        for registro in cursor.execute("SELECT * FROM agenda"):
            print(f"Nome: {registro['nome']}\nTelefone: {registro['Telefone']}")
```

Dessa forma, registro posse ser acessado como se fosse 
um dicionário, no qual o nome do campo é usado como chave. Outra facilidade que essa linha traz é que as chaves são aceitas sem diferenciar se o nome dos campos foi escrito em maiúsculas ou minúsculas. Por exemplo:

```python
f"Nome: {registro['Nome']}\nTelefone: {registro['Telefone']}"
```

## Gerando uma chave primária 🔑

Até agora, trabalhamos apenas com campos normais, ou seja, campos que têm dados. Conforme nossas tabelas crescem, trabalhar apenas com dados pode não ser a melhor solução, e precisaremos acrescentar campos artificiais utilizados para manter o banco de dados como identificadores e marcadores. Uma dessas neccessidades é identificar cada registro de maneira única. Nós podemoos utilizar dados que não se repetem, ou que não deveriam se repetir, como o nome da pessoa, commo a chave primária. Podemos entender uma chave primária como a chave de um dicionário, mas, nesse caso, para tabelas em nosso banco de dados. Qualquer campo ou conjunto de campos podem servir de chave primária. Uma alternativa oferecida pelo SQL é a geração automática de chaves. Nesse caso, o banco se encarrega de criar números únicos para cada registro.

Vamos implementar outro banco de dados, com a população de cada estado do Brasil. Veremos como deixar o SQLite gerar uma chave primária automaticamente:

```sql
CREATE TABLE estados(id INTEGER PRIMARY KEY AUTOINCREMENT, nome TEXT, população INTEGER)
```

Ao criarmos a tabela estados, estamos especificando três campos: ```id```, ```nome``` e ```população```. Veja que ```id``` e ```população``` são do tipo ```INTEGER```, ou seja, os números inteiros (**int**). ```ìd``` é o campo que escolhemos para ser a chave promária dessa tabela, e escrevemos ```PRIMARY KEY AUTOINCREMENT``` para que o SQLite gere esses números automaticamente. Entenda ```id``` como a abreviação de identificador único ou identidade. ```PRIMARY KEY``` significa chave primária.

O programa a seguir cria um banco de dados ```brasil.db```  a tabela ```estados```  e também inclui o nome e população de todos os estados brasileiros. Os dados foram extraídos da Wikipédia (<https://pt.wikipedia.org/wiki/Unidades_federativas_do_Brasil>).

```python
import sqlite3
from contextlib import closing

dados = [
    ["São Paulo", 43663672],
    ["Minas Gerais", 20593366],
    ["Rio de Janeiro", 16369178],
    ["Bahia", 15044127],
    ["Rio Grande do Sul", 11164050],
    ["Paraná", 10997462],
    ["Pernambuco", 9208511],
    ["Ceará", 8778575],
    ["Pará", 7969655],
    ["Maranhão", 6794298],
    ["Santa Catarina", 6634250],
    ["Goiás", 6434052],
    ["Paraíba", 3914418],
    ["Espírito Santo", 3838363],
    ["Amazonas", 3807923],
    ["Rio Grande do Norte", 3373960],
    ["Alagoas", 3300938],
    ["Piauí", 3184165],
    ["Mato Grosso", 3182114],
    ["Distrito Federal", 2789761],
    ["Mato Grosso do Sul", 2587267],
    ["Sergipe", 2195662],
    ["Rondônia", 1728214],
    ["Tocantins", 1478163],
    ["Acre", 776463],
    ["Amapá", 734995],
    ["Roraima", 488072],
]
with sqlite3.connect("brasil.db") as conexão:
    conexão.row_factory = sqlite3.Row
    with closing(conexão.cursor()) as cursor:
        cursor.execute("""create table estados(
                              id integer primary key autoincrement,
                              nome text,
                              população integer
                     )""")
        cursor.executemany("insert into estados(nome, população) values(?,?)", dados)
    conexão.commit()
```

O valor do campo ```id``` será gerado automaticamente. Uma vez que temos a população dos estados, vamos fazer uma consulta para listar os estados em ordem alfabética. Ao executar o próximo programa, observe os valores gerados no campo ```id```, no caso, valores númericos de 1 a 27.

```python
import sqlite3

with sqlite3.connect("brasil.db") as conexão:
    conexão.row_factory = sqlite3.Row
    print(f"{'Id':3s} {'Estado':<20s} {'População':12s}")
    print("=" * 37)
    for estado in conexão.execute("select * from estados order by nome"):
        print(f"{estado['id']:3d} {estado['nome']:<20s} {estado['população']:12d}")
```

A grande diferença é que estamos utilizando a cláusula ```ORDER BY``` para para ordenar os resultados de nossa consulta; nesse caso, pelo campo ```nome```.

```sql
SELECT * FROM estados ORDER BY nome
```

Modifique o programa para que os estados sejam impressos pela população, usando a consulta:

```sql
SELECT * FROM estados ORDER BY população
```

Execute o programa novamente e veja que os estados foram agora impressos pela população, mas da menor para a maior. Embora essa seja a ordem normal, quando trabalhamos com lista de estados por população, esperamos ver do estado mais populoso, ou seja, na ordem inversa (decrescente) dos valores. Vejamos esse resultado ao adicionarmos ```DESC``` após o nome do campo:

```sql
SELECT * FROM estados ORDER BY população DESC
```

## Alterando a tabela

Vamos acrescentar mais alguns campos a nossa tabela de estados. Um campo para a região do Brasil e outro para a sigla do estado. Em SQL, o comando utilizado para alterar os campos de uma tabela é o ```ALTER TABLE```.

```sql
ALTER TABLE estados ADD sigla TEXT
ALTER TABLE estados ADD região TEXT
```

O comando ```ALTER TABLE``` do SQLite é limitado se comparado com outros bancos de dados. Em outros bancos, podem-se alterar vários campos com um só ```ALTER TABLE```, mas, no SQLite não param por aí. Por isso, planeje suas tabelas com cuidadee, caso precise realizar grandes mudanças, prefira criar outra tabela com as alterações e copiar os dados da tabela antiga. Execute o programa para alterar a tabela estados e adicinar os campos sigla e região:

```python
import sqlite3

with sqlite3.connect("brasil.db") as conexão:
    conexão.execute("""alter table estados
                       add sigla text""")
    conexão.execute("""alter table estados
                       add região text""")
```

Agora que a tabela possui os novos campos, vamos alterar nossos registros e preencher a região e sigla a cada estado. Execute o programa:

```python
# Título: Atualizando a tabela de estados para incluir a sigla e região de cada estado
##############################################################################
import sqlite3

dados = [
    ["SP", "SE", "São Paulo"],
    ["MG", "SE", "Minas Gerais"],
    ["RJ", "SE", "Rio de Janeiro"],
    ["BA", "NE", "Bahia"],
    ["RS", "S", "Rio Grande do Sul"],
    ["PR", "S", "Paraná"],
    ["PE", "NE", "Pernambuco"],
    ["CE", "NE", "Ceará"],
    ["PA", "N", "Pará"],
    ["MA", "NE", "Maranhão"],
    ["SC", "S", "Santa Catarina"],
    ["GO", "CO", "Goiás"],
    ["PB", "NE", "Paraíba"],
    ["ES", "SE", "Espírito Santo"],
    ["AM", "N", "Amazonas"],
    ["RN", "NE", "Rio Grande do Norte"],
    ["AL", "NE", "Alagoas"],
    ["PI", "NE", "Piauí"],
    ["MT", "CO", "Mato Grosso"],
    ["DF", "CO", "Distrito Federal"],
    ["MS", "CO", "Mato Grosso do Sul"],
    ["SE", "NE", "Sergipe"],
    ["RO", "N", "Rondônia"],
    ["TO", "N", "Tocantins"],
    ["AC", "N", "Acre"],
    ["AP", "N", "Amapá"],
    ["RR", "N", "Roraima"],
]

with sqlite3.connect("brasil.db") as conexão:
    conexão.executemany(
        """update estados
                           set sigla = ?,
                           região = ?
                           where nome = ?""",
        dados,
    )
```

Agora nosso banco de dados possui uma tabela estados com a população, sigla e região de cada estado. Esses novos campos permitirão utilizarmos funções de agregação da linguagem SQL: ```COUNT```, ```MIN```, ```MAX```, ```AVG``` e ```SUM```.

## Agrupando dados

Um banco de dados pode realizar operações de agrupamento de dados facilmente. Podemos, por exemplo, solicitar o valor mínimo de um grupo de registros, assim como também o máximo ou a média desses valores. No entanto, temos de modificar nossos comandos SQL para indicar como o banco de dados deve agrupar nossos registros.

Vejamos como realizar um grupo simples e exibir quantos registros fazem parte desse grupo, usando a função ```COUNT```. A cláusula SQL que indica agrupamento é ```GROUP BY```, seguida do nome dos campos que compõe o grupo. Imagine que o banco vai concatenar cada um desses campos, criando um valor para cada registro. Vamos chamar esse valor de "chave de grupo". Todos os registros com a mesma chave de grupo fazem parte do mesmo grupo e serão representados por apenas um registro na consulta de seleção. Essa consulta com grupo só pode conter os campos utilizados para compor a chave do grupo e funções de agrupamento de dados, como ```MIN``` (mínimo), ```MAX``` (máximo), ```AVG``` (média, do inglês *average*), SUM (soma) e ```COUNT``` (contagem).

Um exemplo concreto como nosso banco de dados é agrupar os estados por região. A consulta seria algo como:

```sql
SELECT região, count(*) from group by região
```

Esse comando utiliza a cláusula ```GROUP BY``` região para especificar a chave de grupo. Dessa forma, todos os registros que pertencem á mesma região são agrupados. Observe que os campos após o ```SELECT``` incluem região e ```COUNT(*)```. O campo região pôde ser incluído, pois faz parte da chave de grupo especificada em ```GROUP BY```. A função ```COUNT(*)``` retorna quantos registros fazem parte do grupo. Vejamos o resultado do programa:

```python
# Título: Exibindo o número de estados por região
##############################################################################
import sqlite3

print("Região Número de Estados")
print("====== =================")
with sqlite3.connect("brasil.db") as conexão:
    for região in conexão.execute("""
        select região, count(*)
        from estados
        group by região"""):
        print("{0:6} {1:17}".format(*região))
```


Vamos adicionar as funções ```MIN```, ```MAX```, ```SUM``` e ```AVG``` no campo população. Veja o novo programa:

```python
# Título: Exibindo a população mínima, máxima, média e total de cada região
##############################################################################
import sqlite3

print("Região Estados População  Mínima    Máxima      Média    Total (soma)")
print("====== =======          ========= ========== ==========  ============")
with sqlite3.connect("brasil.db") as conexão:
    for região in conexão.execute("""
        select região, count(*), min(população),
               max(população), avg(população), sum(população)
        from estados
        group by região"""):
        print("{0:6} {1:7} {2:18,} {3:10,} {4:10,.0f} {5:13,}".format(*região))
    print(
        "\nBrasil: {0:6} {1:18,} {2:10,} {3:10,.0f} {4:13,}".format(
            *conexão.execute("""
            select count(*), min(população), max(população),
                   avg(população), sum(população) from estados""").fetchone()
        )
    )
```

Conseguimos calcular a população mínima, máxima, média e total de cada região e também para o Brasil. Veja que, na segunda consulta, a que calcula os dados para o Brasil. Veja que, na segunda consulta, a que calcula os dados para o Brasil, não utilizamos a cláusula ```GROUP BY```, podemos continuar usando tudo que já aprendemos em SQL, como as cláusulas ```WHERE``` e ```ORDER BY```. Vejamos o mesmo programa, mas com linhas ordenadas pela população total de cada região em ordem decrescente:

```python
# Título: Ordenando os resultados
##############################################################################
import sqlite3

print("Região Estados População  Mínima    Máxima      Média    Total (soma)")
print("====== =======          ========= ========== ==========  ============")
with sqlite3.connect("brasil.db") as conexão:
    for região in conexão.execute("""
        select região, count(*), min(população),
               max(população), avg(população), sum(população)
        from estados
        group by região
        order by sum(população) desc"""):
        print("{0:6} {1:7} {2:18,} {3:10,} {4:10,.0f} {5:13,}".format(*região))
    print(
        "\nBrasil: {0:6} {1:18,} {2:10,} {3:10,.0f} {4:13,}".format(
            *conexão.execute("""
            select count(*), min(população), max(população),
                   avg(população), sum(população) from estados""").fetchone()
        )
    )
```

Veja que escrevemos `SUM(população) as tpop`, dando o nome `tpop` à soma. Esse tipo de construção evita a repetição da função na consulta e facilita a leitura.

Resultado da execução do programa:

```
Região Estados População  Mínima    Máxima      Média    Total (soma)
====== =======          ========= ========== ==========  ============
SE           4          3,838,363 43,663,672 21,116,145    84,464,579
NE           9          2,195,662 15,044,127  6,199,406    55,794,654
S            3          6,634,250 11,164,050  9,598,587    28,795,762
N            7            488,072  7,969,655  2,426,212    16,983,485
CO           4          2,587,267  6,434,052  3,748,298    14,993,194

Brasil:     27            488,072 43,663,672  7,445,618   201,031,674
```

Podemos também filtrar os resultados após o agrupamento, usando a cláusula `HAVING`. Para entender a diferença entre `WHERE` e `HAVING`, imagine que `WHERE` é executada antes antes do agrupamento, selecionando os registros que farão parte do resultado, antes de o agrupamento ser realizado. A cláusula `HAVING` avalia o resultado do agrupamento e decide quais farão parte do resultado final. Por exemplo, podemos escolher apenas regiões com mais de cinco estados. Como a quantidade de estados por região só é conhecida após o agrupamento ('GROUP BY'), essa condição deve aparecer em uma cláusula `HAVING`.

```python
select região, count(*), min(população),
           max(população), avg(população), sum(população) as tpop
           from estados group by região
       having count(*) > 5
           order by tpop desc
```

Veja o programa completo utilizando `HAVING`:

```python
# Título: Listando apenas as regiões com mais de 5 estados
##############################################################################
import sqlite3

print("Região Estados População  Mínima    Máxima      Média    Total (soma)")
print("====== =======          ========= ========== ==========  ============")
with sqlite3.connect("brasil.db") as conexão:
    for região in conexão.execute("""
        select região, count(*), min(população),
               max(população), avg(população), sum(população) as tpop
        from estados
        group by região
        having count(*) > 5
        order by tpop desc"""):
        print("{0:6} {1:7} {2:18,} {3:10,} {4:10,.0f} {5:13,}".format(*região))
```

Resultando em:

```
    Região Estados População  Mínima    Máxima      Média    Total (soma)
====== =======          ========= ========== ==========  ============
NE           9          2,195,662 15,044,127  6,199,406    55,794,654
N            7            488,072  7,969,655  2,426,212    16,983,485
```

Uma vez que apenas as regiões Norte (N) e Nordeste(NE) possuem mais de cinco estados.


## Trabalhando com datas

Embora o SQLite trabalhe com datas, o tipo date não é suportado diretamente gerando uma certa confusão entre datas e strings. Vamos criar uma tabela com um campo do tipo data.

```python
# Título: Criando e populando uma tabela com feriados
##############################################################################
import sqlite3

feriados = [
    ["2018-01-01", "Confraternização Universal"],
    ["2018-04-21", "Tiradentes"],
    ["2018-05-01", "Dia do trabalhador"],
    ["2018-09-07", "Independência"],
    ["2018-10-12", "Padroeira do Brasil"],
    ["2018-11-02", "Finados"],
    ["2018-11-15", "Proclamação da República"],
    ["2018-12-25", "Natal"],
]
with sqlite3.connect("brasil.db") as conexão:
    conexão.execute(
        "create table feriados(id integer primary key autoincrement, data date, descrição text)"
    )
    conexão.executemany("insert into feriados(data,descrição) values (?,?)", feriados)
```


Criamos a tabela feriados e inserimos algumas datas. Observe que escrevemos as datas no formato ISO 8601 (<https://pt.wikipedia.org/wiki/ISO_8601>), ou seja: ANO-MÊS-DIA. Nesse formato, a data do Natal (25/12/2018) é escrita como 2018-12-25. Escrever as datas nesse formato é uma característica do SQLite. Sempre escreva sua datas no formato ISO ao trabalhar com esse gerenciador de banco de dados. Observe que utilizamos o tipo `date` (data) na coluna data. Modifique o ano de 2018 para o ano corrente, caso necessário.

Vejamos como acessar esses valores no programa:

```python
# Título: Exibindo os feriados
##############################################################################
import sqlite3

with sqlite3.connect("brasil.db") as conexão:
    for feriado in conexão.execute("select * from feriados"):
        print(feriado)

```

Que resulta em:

```
(1, '2018-01-01', 'Confraternização Universal')
(2, '2018-04-21', 'Tiradentes')
(3, '2018-05-01', 'Dia do trabalhador')
(4, '2018-09-07', 'Independência')
(5, '2018-10-12', 'Padroeira do Brasil')
(6, '2018-11-02', 'Finados')
(7, '2018-11-15', 'Proclamação da República')
(8, '2018-12-25', 'Natal')

```



Acessamos o campo data como fazemos até então, sem algum procedimento especial. Veja que, ao imprimirmos a tupla `feriado` com o resultado de nossa seleção, o campo `data` foi impresso como uma string qualquer. Nada impede que utilizemos strings para representar datas, como fizemos ao criar o banco de dados, mas campos do tipo data são mais interessantes, pois podemos facilmente consultar o dia da semana e também realizar operações com datas.

Vamos modificar nossa conexão com o SQLite de forma a solicitar o processamento dos tipos de campo em nossas consultas. Ao solicitarmos a conexão, devemos passar `detect_types=sqlite3.PARSE_DECLTYPES` como parâmetro. Vejamos o novo programa com essa modificação:

```python
# Título: Convertendo datas em datetime
##############################################################################
import sqlite3

with sqlite3.connect("brasil.db", detect_types=sqlite3.PARSE_DECLTYPES) as conexão:
    for feriado in conexão.execute("select * from feriados"):
        print(feriado)

```

O resultado é bem diferente:

```
(1, datetime.date(2018, 1, 1), 'Confraternização Universal')
(2, datetime.date(2018, 4, 21), 'Tiradentes')
(3, datetime.date(2018, 5, 1), 'Dia do trabalhador')
(4, datetime.date(2018, 9, 7), 'Independência')
(5, datetime.date(2018, 10, 12), 'Padroeira do Brasil')
(6, datetime.date(2018, 11, 2), 'Finados')
(7, datetime.date(2018, 11, 15), 'Proclamação da República')
(8, datetime.date(2018, 12, 25), 'Natal')
```


Veja que os valores do campo `data` agora são objetos da classe `datetime.date`. Isso evita termos de fazer a conversão manualmente de string para `datetime.date`.

Agora vamos utilizar o método `strftime` do objeto da classe `datetime.date` para exibir apenas o dia o mês da data, sem ano:

```python
# Título: Exibição parcial da data
##############################################################################
import sqlite3

with sqlite3.connect("brasil.db", detect_types=sqlite3.PARSE_DECLTYPES) as conexão:
    conexão.row_factory = sqlite3.Row
    for feriado in conexão.execute("select * from feriados"):
        print(f"{feriado['data'].strftime('%d/%m')} {feriado['descrição']}")

```



Voltamos a utilizar `row_factory` para acessarmos os campos por nome, como em dicionário. O método `strftime` foi utilizado com a máscara `%d/%m` para exibir apenas o dia e o mês. Você pode verificar os formatos aceitos por `strftime` na tabela abaixo:

|**Código**|**Descrição**|
|:----:|:---|
|%a|dia da semana abreviado|
|%A|nome do dia da semana|
|%b|nome do mês abreviado|
|%B|nome do mês completo|
|%c|data e hora conforme configuração regional|
|%d|dia do mês (01-31)|
|%H|hora do formato 24 h (00-23)|
|%I|hora no formato 12 h|
|%j|dia do ano 001-366|
|%m|mês (01-12)|
|%M|minutos (00-59)|
|%p|AM ou PM|
|%S| segundos (00-61)|
|%U|número da semana (00-53), em que a semana 1 começa no primeiro domingo|
|%w|dia da semana (0-6), em que 0 é o domingo|
|%W|número da semana (00-53), em que a semana 1 começa após a primeira segunda-feira|
|%x|representação regional da data|
|%X|representação regional da hora|
|%y|ano (00-99)|
|%Y|ano com 4 dígitos|
|%Z|nome do fuso horário|
|%|símbolo de %|

Vejamos o resultado do programa:

```
01/01 Confraternização Universal
21/04 Tiradentes
01/05 Dia do trabalhador
07/09 Independência
12/10 Padroeira do Brasil
02/11 Finados
15/11 Proclamação da República
25/12 Natal
```

Faça uma pesquisa no texto acima e cite os principais comandos encontrados em SQL: